name: z2apd_datasorter
description: "z2apd_datasorter - For internal use only"
publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.4
  file_picker: ^8.1.6
  desktop_drop: ^0.4.4
  path: ^1.9.0
  http: ^1.2.0
  archive: ^4.0.2
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
